### ISSUE TITLE
Implement spinner or different kind of proper feedback into claim dialog to visualize the moment when days are being fetched.

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vether-burn#4]

**Comment by 0xBrian** [comment]
Aside from providing some kind of feedback that data is being fetched after selecting an era, I'd like to clear and disable the days dropdown immediately, and then enable it again once it's populated with the days for that era.

Do you have any guidance about what UI elements to use for the spinner? Just something appropriate from Chakra UI?

**Comment by yellowgh0st** [comment]
Alright, you can put _disabled_ on the input.
Sure, Chakra has the most basic block stacks we need to build more complex components.

Use this https://chakra-ui.com/docs/feedback/spinner and put it somewhere close to the input.
Or I would try to use https://chakra-ui.com/docs/feedback/progress#animated-progress
That maybe even better. You will probably need to define it in our theme to match our style.
(https://github.com/vetherasset/vether-burn/tree/main/src/themes/vether)
I may try to improve the composition later if needed.

I was also thinking of central progress line above the header which could indicate when something is loading across the app (whatever is that), but that might be implemented later after we have what you describe anyways.

**Comment by yellowgh0st** [comment]
Merged in 4a1d88b
