### ISSUE TITLE
Create footer or contextual button to provide access to the info materials.

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vether-burn#9]

**Comment by yellowgh0st** [comment]
I'm still not sure what way to go.

**Examples**
1. Uniswap's context button

![Screenshot from 2021-04-11 13-27-24](https://user-images.githubusercontent.com/34014106/114302598-04d3e900-9aca-11eb-9e7f-5a0d183b3628.png)

2. 1inch's standard footer

![Screenshot from 2021-04-11 13-28-06](https://user-images.githubusercontent.com/34014106/114302609-11f0d800-9aca-11eb-8682-332a25139435.png)


What do you think?

**Comment by 0xBrian** [comment]
Hmm, I think it'd be best to do both. Seems inoffensive, because it's just a small button at the top (unless they want to open it) or a row at the bottom with label links for stuff like the whitepaper and icons for standard social media stuff (or maybe two rows at the bottom, one of icons and one of label links)

**Comment by yellowgh0st** [comment]
Sounds good, but there's very little space in mobile header, it's gonna be very bad composition.

**Comment by yellowgh0st** [comment]
We'll make the button for desktop, but we'll put the info into footer on mobile and make the button gone.
